---
#spring:
# datasource:
# password: 123456
    # filters: log4j,stat,wall
    #type: com.alibaba.druid.pool.DruidDataSource
    # driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/ssmbuild?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    # username: root
    #messages:
    #basename: i18n.login
    #mvc:
    #static-path-pattern: /**
    #date-format: yyyy-MM-dd
    #thymeleaf:
    # cache: false
    #mybatis:
  # mapper-locations: classpath:mybatis/mapper/*.xml,classpath:mapper/*.xml
# type-aliases-package: com.nan.pojo

#logging:
    #  level:
  #   root: info

